## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
# This piece of code prompts to choose file
from google.colab import files
uploaded = files.upload()
# After choosing file use this piece of code
import io
application_df = pd.read_csv(io.BytesIO(uploaded['charity_data.csv']))
# application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

Saving charity_data.csv to charity_data.csv

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'],axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_count = application_df['APPLICATION_TYPE'].value_counts()
application_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_count[application_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count[classification_count > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace= application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts()<1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
X_dummies = pd.get_dummies(application_df)

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X= X_dummies.drop('IS_SUCCESSFUL',axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train[0])
hidden_layer1 =  80
hidden_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, activation="relu", input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.5688 - accuracy: 0.7243
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5555 - accuracy: 0.7268
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5534 - accuracy: 0.7299
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7311
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5486 - accuracy: 0.7322
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7314
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7316
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7328
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5459 - accuracy: 0.7317
Epoch 12/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5457 - accuracy: 0.7343
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7331
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7329
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7340
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7352
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7349
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5432 - accuracy: 0.7356
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7363
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7361
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7358
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5426 - accuracy: 0.7356
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7358
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7358
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7367
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5412 - accuracy: 0.7367
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7371
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7363
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7376
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7364
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7383
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5400 - accuracy: 0.7368
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7367
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7371
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7368
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7378
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5391 - accuracy: 0.7378
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7374
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7383
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7384
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7376
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7377
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.7368
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7392
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7380
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7374
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5378 - accuracy: 0.7398
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7388
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7385
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7386
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7385
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7379
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7396
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7381
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5366 - accuracy: 0.7390
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7391
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7391
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5365 - accuracy: 0.7386
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7387
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7385
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7388
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7385
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7392
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7380
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7397
Epoch 76/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5360 - accuracy: 0.7387
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7397
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7394
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7390
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7398
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7394
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7393
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7390
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7392
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7400
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7391
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7393
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7398
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7398
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7394
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7399
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7393
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7395
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7392
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7394
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7401

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5621 - accuracy: 0.7269 - 1s/epoch - 4ms/step
Loss: 0.5621384382247925, Accuracy: 0.7268804907798767

In [18]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')